FROM golang:latest as build

LABEL owner="CJC Software Solutions"
LABEL author="Chris Clarkson"

RUN mkdir -p $GOPATH/src/github.com/ClarksonCJ/grpc-in-docker/
RUN mkdir -p /opt/output

WORKDIR $GOPATH/src/github.com/ClarksonCJ/grpc-in-docker/

COPY . .

RUN go get ./...

RUN go build -o /opt/output/server cmd/server/main.go

FROM golang:latest

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY --from=build /opt/output/server ./

ENTRYPOINT ["/opt/app/server"]
CMD ["--Port", ":30551"]
